name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libudev-dev
    - name: Build
      run: cargo build --no-default-features --features linux-static-hidraw --verbose
    - name: Run tests
      run: cargo test --no-default-features --features linux-static-hidraw --verbose
